/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Produced by `pnpm contracts:generate` from the FastAPI OpenAPI schema, which is derived from the
 * Pydantic models in apps/api. AGENTS.md §6:
 *
 *   "The frontend imports types only from @asebe/contracts. Hand-written `interface Post { … }`
 *    in apps/web is forbidden — it will drift and nothing will catch it."
 *
 * An edit made here is lost on the next generation, and CI will fail on the resulting diff.
 * To change a type, change the Pydantic model and regenerate.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness only. Touches nothing external, so it cannot fail for an infrastructure reason.
         *
         *     README requires no user-visible string to be hardcoded (R13); the value returned here is a
         *     machine-readable literal, not interface text, so it is not subject to that rule. Anything a
         *     user reads is resolved from ``packages/contracts`` message keys.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports readiness, never raises for an infrastructure failure.
         *
         *     Not yet wired to a real check: the database layer is not functional in this increment (no
         *     PostgreSQL available — see docs/architecture.md §9 and the increment notes). Reporting
         *     ``not_configured`` is accurate and, importantly, is not the same claim as ``unreachable``.
         *
         *     When the database lands, this must perform a real round-trip. Leaving it returning a constant
         *     ``ready`` would be exactly the "claim success we cannot prove" failure AGENTS.md §2 forbids,
         *     applied to infrastructure rather than to publishing.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthResponse
         * @description Response model. Per AGENTS.md §6 this is the single source of truth for the wire format,
         *     and any change to it is a breaking frontend change requiring a contract regeneration.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "reachable" | "unreachable" | "not_configured";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
