"""initial publishing tables

Revision ID: ac84bed5dfb3
Revises:
Create Date: 2026-10-02 09:42:06.062789
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ac84bed5dfb3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("preferred_language", sa.String(length=16), server_default="en", nullable=False),
        sa.Column("time_zone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "notification_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "onboarding_status", sa.String(length=32), server_default="not_started", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "content_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_content_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_index(op.f("ix_content_items_user_id"), "content_items", ["user_id"], unique=False)
    op.create_table(
        "platform_posts",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("platform_caption", sa.Text(), nullable=True),
        sa.Column("platform_title", sa.String(length=500), nullable=True),
        sa.Column("platform_thumbnail_url", sa.Text(), nullable=True),
        sa.Column("platform_alt_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("platform_post_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("scheduled_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_time_zone", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'STATUS_UNKNOWN', 'CANCELLED', 'REQUIRES_AUTHENTICATION', 'REQUIRES_USER_REVIEW')",  # noqa: E501
            name=op.f("ck_platform_posts_platform_posts_status_known"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_platform_posts_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_posts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_posts")),
        sa.UniqueConstraint("content_item_id", "platform", name="content_item_platform"),
    )
    op.create_index(
        op.f("ix_platform_posts_content_item_id"),
        "platform_posts",
        ["content_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_posts_scheduled_at_utc"),
        "platform_posts",
        ["scheduled_at_utc"],
        unique=False,
    )
    op.create_index(
        "ix_platform_posts_status_scheduled",
        "platform_posts",
        ["status", "scheduled_at_utc"],
        unique=False,
    )
    op.create_index(op.f("ix_platform_posts_user_id"), "platform_posts", ["user_id"], unique=False)
    op.create_table(
        "publishing_attempts",
        sa.Column("platform_post_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("request_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=64), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempt_number >= 1", name=op.f("ck_publishing_attempts_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["platform_post_id"],
            ["platform_posts.id"],
            name=op.f("fk_publishing_attempts_platform_post_id_platform_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publishing_attempts")),
        sa.UniqueConstraint("platform_post_id", "attempt_number", name="post_attempt_number"),
    )
    op.create_index(
        op.f("ix_publishing_attempts_platform_post_id"),
        "publishing_attempts",
        ["platform_post_id"],
        unique=False,
    )
    op.create_index(
        "ix_publishing_attempts_post_started",
        "publishing_attempts",
        ["platform_post_id", "request_started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_publishing_attempts_post_started", table_name="publishing_attempts")
    op.drop_index(op.f("ix_publishing_attempts_platform_post_id"), table_name="publishing_attempts")
    op.drop_table("publishing_attempts")
    op.drop_index(op.f("ix_platform_posts_user_id"), table_name="platform_posts")
    op.drop_index("ix_platform_posts_status_scheduled", table_name="platform_posts")
    op.drop_index(op.f("ix_platform_posts_scheduled_at_utc"), table_name="platform_posts")
    op.drop_index(op.f("ix_platform_posts_content_item_id"), table_name="platform_posts")
    op.drop_table("platform_posts")
    op.drop_index(op.f("ix_content_items_user_id"), table_name="content_items")
    op.drop_table("content_items")
    op.drop_table("users")
    # ### end Alembic commands ###
